spring.application.name=userapi

spring.datasource.url=jdbc:postgresql://localhost:5432/devdb
spring.datasource.username=davi
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tells Flyway to only work within the public schema
spring.flyway.schemas=public

# Tells Hibernate to create tables in the public schema
spring.jpa.properties.hibernate.default_schema=public
